### ISSUE TITLE
No credentials supplied

### ISSUE THREAD

**Issue by JongYunSong** [watson-intu/self-docs#2]
Hi, I've followed Intu project's workshop and got some problem when I ran Intu service.

In my bluemix account, several api credentials exist as below.
![application list](https://cloud.githubusercontent.com/assets/16532575/24130107/0a9fe388-0e2a-11e7-9806-68a9658b6aa3.png)

And copied & pasted credential information to Intu Gateway - Manage - Service as below.
![credential_api](https://cloud.githubusercontent.com/assets/16532575/24130132/33beab82-0e2a-11e7-9d87-51bb20673667.PNG)

But at workshop1, when I ran Intu service, error output was printed as below.
![error0](https://cloud.githubusercontent.com/assets/16532575/24130165/56e32a70-0e2a-11e7-92e4-3438fbc2804c.PNG)

I ignored and passed through to workshop3, I filled body.json of self-sdk-master as proposed. 
When I ran self-sdk project, this output was printed.
![error](https://cloud.githubusercontent.com/assets/16532575/24131033/8301d890-0e2f-11e7-88aa-f48221b4679c.PNG)

I didn't copied & pasted Intu credential information to nowhere because it wasn't used in workshop.
![credential_intu](https://cloud.githubusercontent.com/assets/16532575/24130259/dc03bbfc-0e2a-11e7-80f5-23b1f7500152.PNG)

I think I missed something at first time and got same error repeatedly. Can I get some help?

Thank you.

**Comment by rlyle** [comment]
Closing this out, since the gateway is basically going away for the most part.
