### ISSUE TITLE
Specify Voice and other parameters for Text to Speech API etc.

### ISSUE THREAD

**Issue by georg90** [watson-intu/self-docs#3]
Hello!

https://stackoverflow.com/questions/43130043/how-to-change-params-like-language-or-voice-on-ibm-project-intu-setup-on-a-raspb

Since there was no reply to this question, I am asking it here.

How can one change the voice for intu?

I am using Intu on my Mac, and when I change the voice inside the `body.json`, the change is ignored and "Michael" is greeting me again.

**Comment by rolyle** [comment]
search for "SpeakingAgent", change the m_Language & m_Gender values to change the voice.

**Comment by georg90** [comment]
Thanks for the quick reply. That worked!

The Watson Text-to-Speech API supports a feature called "type" where you can give the voice a more "youthful" sound. 
Is this also possible with intu?

Background is: We want to let NAO sound more like the original voice he has. So not the strong American "Michael" but also not female..if you know what I mean.

I will ping you within IBM, so we can have a direct chat, if that's ok.

**Comment by georg90** [comment]
Also the speaking rate can be tweaked with SSML. Is there a way to slow it down with project intu?

https://www.ibm.com/watson/developercloud/doc/text-to-speech/SSML.html#speak_tag

**Comment by rlyle** [comment]
You can take a look at the SpeakingAgent.cpp/h, we have open sourced the code that works with the SSML. You can implement your own SpeakingAgent, then override the core implementation using the REG_OVERRIDE_SERIALIZABLE() macro.
