### ISSUE TITLE
Failing to parse config.json in Raspi

### ISSUE THREAD

**Issue by Danizu** [watson-intu/self-docs#4]
Hello,
I'm following the instruction to have intu running in a raspberry.
I've copied my credentials from INTU gw to config.json but run_self.sh fails to correctly parse the file. The 
error message is.
 failed to parse line 1 column 1 syntax error: value, object or array expected

this is the credential json format I get from INTU gw:

{ "m_BearerToken": "eyJhbGciOiJIUzI1Ni.......Jfzlw" ,
		"m_GatewayURL" : "https://rg-gateway.mybluemix.net",
		"m_GroupId": "fbfc53412cef480c88d54d90b1d6ce99",
		"m_OrgId": "d435dc35b3aef6d630485151668c101f"
		}

**Comment by rlyle** [comment]
This appears to be something wrong with the formatting of your config.json, can you attach the full file as an attachment to this issue.. (just drag and drop the file into this field, see the comment below this edit box).

**Comment by Danizu** [comment]
The config.json is identical to credentials obtained from INTU GW:
I go to INTu gw -> view credentials -> select org and group and then get credentials I copy and paste the json with credentials in the config.json.
This is the structure of the json:

		{ "m_BearerToken": "eyJhbGciOiJIU------" ,
		"m_GatewayURL" : "https://rg-gateway.mybluemix.net",
		"m_GroupId": "fbfc53412cef480c88d54d90b1d6ce99",
		"m_OrgId": "d435dc35b3aef6d630485151668c101f"
		}
